@startuml
start
:登录系统;
:浏览课程列表;
if (选择课程) then (是)
    :进入课程详情页;
    :查看课程资源;
    if (选择资源) then (是)
        :学习资源;
        :更新学习进度;
        if (完成资源学习) then (是)
            :标记资源为已完成;
        endif
    endif
    if (有作业) then (是)
        :查看作业详情;
        :撰写作业;
        :上传作业文件;
        :提交作业;
    endif
    if (有测试) then (是)
        :开始测试;
        :回答问题;
        :提交测试;
        :查看测试成绩;
    endif
endif
stop

@enduml
